name: uniled_pro_v2
description: Universal BLE LED Controller with Keyless-Go
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
